global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-exporter:9308']

  - job_name: 'ksqldb'
    static_configs:
      - targets: ['ksqldb-server:9998']
